### ISSUE TITLE
OtherError in not a valid JSON RPC 2.0 error response

### ISSUE THREAD

**Issue by scls19fr** [cenobites/flask-jsonrpc#22]
Hello,

error OtherError message looks like

    {
      "code": -32001,
      "data": null,
      "message": "OtherError: Invalid Terminal ID u'tid01x'",
      "name": "OtherError"
    }

but a a malformed JSON RPC request error looks like

    {
        "error": {
            "code": -32000,
            "message": "Not a valid JSON RPC request"
        },
        "id": null,
        "jsonrpc": "2.0"
    }

Every error message should be JSON RPC 2.0 error response
moreover they can sometimes have `id` different from `null` so
we should provide a way to set id (maybe in constructor with id=None as default value)

Kind regards

**Comment by nycholas** [comment]
Fixed in version 0.3.

Thank you.
