### ISSUE TITLE
incompatible with http.headers 'Content-Type':'application/json-prc'

### ISSUE THREAD

**Issue by hualongsd** [cenobites/flask-jsonrpc#222]
Hello, some languages' jsonrpc toolkit specific that  'Content-Type':'application/json-prc'. For example,  the JsonRpcBasicServer.java for java. But, now the flask-jsonrpc don't support 'Content-Type':'application/json-prc'.
Could you change the FUNC is_json() in /src/site.py line 95? So that make it compatible with java's jsonrpc tool, and support 'Content-Type':'application/json-prc'.

**Comment by nycholas** [comment]
Hi @hualongsd,

It is a very strange Content-Type to JSON-RPC, but I think we can put this configuration on set up of JSON-RPC:

```
from flask import Flask
from flask_jsonrpc import JSONRPC

app = Flask("application")
jsonrpc = JSONRPC(app, "/api", enable_web_browsable_api=True, headers_allow_list={'Accept': 'application/json-rpc'})
``` 

Something like that. I will evaluate that.


Thank you.

**Comment by hualongsd** [comment]
Hello nycholas, 

Thank you for your prompt reply. 

And thank you for your willingness to help solve my problem. I'm looking forward to the new version being 'application/json-rpc' compatible.

Have a good day.

**Comment by nycholas** [comment]
@hualongsd I will release a new version this weekend with these modifications.

Thank you.

**Comment by nycholas** [comment]
@hualongsd version 2.2.1[1] was released with its changes, thank you for your contribution.

[1] - https://pypi.org/project/Flask-JSONRPC/2.2.1/

**Comment by hualongsd** [comment]
Hello nycholas,

Well noted.

Thank you very much for dealing with this problem so efficiently. That helps me to deliver my work on time.

Have a good weekend.
