### ISSUE TITLE
Logging approach creates redundant events on each exception

### ISSUE THREAD

**Issue by Kaveshnikov** [cenobites/flask-jsonrpc#258]
Hello. I use this library in one of my projects. I have noticed that across the library codebase on each exception 2 logging records are created. This approach complicates integrations with errors monitoring solutions, for example Sentry. An event will be created on each logging record. For example, a record with message "unexpected error" (created [here](https://github.com/cenobites/flask-jsonrpc/blob/08e065142f9414bb085b702e4a92266ce48b757a/src/flask_jsonrpc/site.py#L147)) doesn't provide any valuable information for the investigation. Also, `logging.Logger.exception()` method is not supposed to be used like [that](https://github.com/cenobites/flask-jsonrpc/blob/08e065142f9414bb085b702e4a92266ce48b757a/src/flask_jsonrpc/site.py#L148). It will get the Exception object implicitly and log the traceback by default. So, we only need to provide some meaningful message as an argument for this method. 

I suggest to refactor all places with such an approach to create only one logging record. For example, in [this place](https://github.com/cenobites/flask-jsonrpc/blob/08e065142f9414bb085b702e4a92266ce48b757a/src/flask_jsonrpc/site.py#L147) it will be like this:
```python
current_app.logger.exception('unexpected error')
```

**Comment by nycholas** [comment]
Hi @Kaveshnikov,

> I suggest to refactor all places with such an approach to create only one logging record. For example, in [this place](https://github.com/cenobites/flask-jsonrpc/blob/08e065142f9414bb085b702e4a92266ce48b757a/src/flask_jsonrpc/site.py#L147) it will be like this:
`
current_app.logger.exception('unexpected error')`

The excellent suggestion, I will accept that. 
A new medium release will be launched.  

Thank you.

**Comment by nycholas** [comment]
Some examples to further information:

```
>>> try:
...     1/0
... except ZeroDivisionError as e:
...     logging.exception('xxx')
...
...
ERROR:root:xxx
Traceback (most recent call last):
  File "<bpython-input-9>", line 2, in <module>
    1/0
ZeroDivisionError: division by zero
```

```
>>> try:
...     1/0
... except ZeroDivisionError as e:
...     logging.error('xxx')
...
...
ERROR:root:xxx
```

```
>>> try:
...     1/0
... except ZeroDivisionError:
...     logging.exception('xxx')
...
...
ERROR:root:xxx
Traceback (most recent call last):
  File "<bpython-input-23>", line 2, in <module>
    1/0
ZeroDivisionError: division by zero
```

```
>>> try:
...     1/0
... except:
...     import logging
...     logging.exception('xxx')
...
...
ERROR:root:xxx
Traceback (most recent call last):
  File "<bpython-input-30>", line 2, in <module>
    1/0
ZeroDivisionError: division by zero
```
