### ISSUE TITLE
High load?

### ISSUE THREAD

**Issue by byaka** [cenobites/flask-jsonrpc#27]
When i'm give high load (5-10 connections at second from browsers via ajax) on simple server, writen with this lib, i have 'connection timed out'.
Without high load all work fine. 
all json-rpc methods simple and no any special (no db connections or any long operations).

**Comment by nycholas** [comment]
Hello,

I do not see a reason, but it would be great this case for performance testing.

You can show off your example?

Thank you.

**Comment by byaka** [comment]
i'm find then Flask in standart use allow only one connection per time.
Key threaded=True solve this (but ofcourse give some problems).
i'm watch to gevent as standalone wsgi container for flask in prodaction.
