### ISSUE TITLE
Query ids are not returned correctly

### ISSUE THREAD

**Issue by ne0h** [cenobites/flask-jsonrpc#33]
Hi,

we are currently writing a small, encrypted chat service with json-rpc. While reporting an issue to the json-rpc implementation we use on client-side, we think that we might found an additional bug in this implementation.

Here is a description of the bug: https://github.com/cinemast/libjson-rpc-cpp/issues/119#issuecomment-124474319

Thanks in advance!

**Comment by nycholas** [comment]
Fixed in version 0.3.
