### ISSUE TITLE
Feature reqest: do not allow to invoke method as JSON-RPC "Notification"

### ISSUE THREAD

**Issue by Talkless** [cenobites/flask-jsonrpc#369]
I have spend hours debugging why I get 204 NO CONTENT when view does return data... Just because I've forgot to add "id:0" into JSON-RPC request...

It seem there's no way to check if it's notification or not? I would actually throw error if heavyweight request is ignored...

**Comment by nycholas** [comment]
@Talkless please review the PR #385 for your considerations 🙏
