### ISSUE TITLE
Add extended data validation library support for method parameters

### ISSUE THREAD

**Issue by zmingee** [cenobites/flask-jsonrpc#37]
There's currently some basic data validation for methods, but it only supports type validation (i.e., verify parameter is `dict`, `int`, `str`, etc.). It would be nice if users could utilize an external library like [Cerberus](http://cerberus.readthedocs.org/en/latest/index.html) to validate the data inside the extension rather than unpacking all of the variables inside of the view itself. 

I could probably get the feature implemented myself and submit a pull request, but as I said in the last issue report I opened, there aren't any contributing guidelines so I'm not sure what the next step of that would be.

**Comment by nycholas** [comment]
Hello,

Very cool this project that would help a lot.
Would be some changes that break old code, then I will look for the next version.

Thank you.
