### ISSUE TITLE
Arg injection for JSONRPC.method decorator assumes authentication parameter names 

### ISSUE THREAD

**Issue by dmaestas** [cenobites/flask-jsonrpc#39]
This is currently marked as a TODO. An optional keyword arg to the JSONRPC constructor could allow a class or function to used to provide application specific argument injection.

**Comment by nycholas** [comment]
Hello,

I'm not sure if the jsonrpc treat authentication, perhaps a decorator for this, what do you think?

Thank you.

**Comment by dmaestas** [comment]
I made the change to be as similar as possible to the way you had set up the assumption with the TODO. I use HTTP authentication, while I recognize others may use injected method parameters. I like the idea of a decorator, but it would break your auto tests for the pull request. Give me the weekend to think about it. I can send you the proposed change for review. If you like, I'll make it happen.

Dave


Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 1/29/2016 7:02:14 AM, Nycholas de Oliveira e Oliveira <notifications@github.com> wrote:
Hello,
I'm not sure if the jsonrpc treat authentication, perhaps a decorator for this, what do you think?
Thank you.

**Comment by nycholas** [comment]
Hello,

When I say "maybe a decorator for it," would remove the complete authentication of RPC json, and leave this responsibility to another library of choice.

I will review and accept your PR.
For next version, I'll keep this approach.

Thank you.
