### ISSUE TITLE
The documentation for blueprints isn't clear on how they work

### ISSUE THREAD

**Issue by offbyone** [cenobites/flask-jsonrpc#41]
I'd like to know how blueprints actually work in Flask-JSONRPC; the only thing the examples look to be doing is registering the blueprint itself, but the methods on it are registered to the toplevel JSONRPC instance, instead of one for the blueprint itself:

``` python
from base_app import jsonrpc  # the one from the toplevel app
from flask import Blueprint

bp = Blueprint(__name__)

# if I had a method here:
@bp.route("/')
def method():
    pass

# but for the JSONRPC, the blueprint doesn't seem to be used:
@jsonrpc.method("BluePrint.a_method")
def a_method():
    pass
```

I'd expect something like this:

``` python
from flask_jsonrpc import JSONRPC
from flask import Blueprint

bp = Blueprint(__name__)
bprpc = JSONRPC(blueprint=bp)

@bprpc.method("a_method")
def a_method():
    pass

from base_app import jsonrpc
jsonrpc.register_blueprint("TopLevel", bprpc)
```

This would end up being called as TopLevel.a_method.

I'm not sure this makes sense, but it lines up with my intuition about how blueprints work.

**Comment by nycholas** [comment]
Hello,

True, this make sense.
I will analyze the changes for refactory, if you have a pull request, will welcome, ;).

Thank you.

**Comment by nycholas** [comment]
Hi,

In new release (1.0.0) was modified, look at: https://github.com/cenobites/flask-jsonrpc/blob/release/v1.0.0/tests/test_app.py#L187.

Thank you.
