### ISSUE TITLE
Document how to use the local werkzeug client to unittest JSONRPC apps

### ISSUE THREAD

**Issue by offbyone** [cenobites/flask-jsonrpc#42]
I'm not actually sure at all how to do this :)

**Comment by marthinus-engelbrecht** [comment]
Hi man, thanks for this module. 

I got this working. I can do a pull request on the documentation if you open to it?

**Comment by nycholas** [comment]
@marthinus-engelbrecht yes, of course.

Thank you!

**Comment by nycholas** [comment]
[Here](https://github.com/cenobites/flask-jsonrpc/blob/master/tests/test_client.py#L30) example of the test with pytest.
