### ISSUE TITLE
remove support for 3.7 and 3.8 and add 3.12

### ISSUE THREAD

**Issue by alexted** [cenobites/flask-jsonrpc#430]
@nycholas Do you plan to remove support for 3.7 and 3.8 and add 3.12?

**Comment by nycholas** [comment]
@alexted Yes, I have been working on that. Also, add support to Flask 3.0.

**Comment by nycholas** [comment]
I was intent to put together more features and issues, do you need this upgrade? Let me know, I can delivery it faster.

**Comment by nycholas** [comment]
@alexted for the next week I will generate a new version of Flask-JSONRPC which will be 3.0.0, see [here](https://github.com/cenobites/flask-jsonrpc/pull/431) the changes requested.

Thank you!

**Comment by nycholas** [comment]
@alexted I saw `ruff` and it sounds good! I will verify that to implement on the project, by the way, version 3.0.0 was released, see [here](https://pypi.org/project/Flask-JSONRPC/3.0.0/).

Thank you.
