### ISSUE TITLE
Authentication backend assumes username and password  (was marked as ToDo)

### ISSUE THREAD

**Issue by robinvanleeuwen** [cenobites/flask-jsonrpc#44]
In **init**.py (line 228-229) the authentication backend assumes that a username and password is given in the check_auth function that is given in the api.method(...., authenticated=check_auth) function. 

```
# TODO: this is an assumption
X['arg_names'] = ['username', 'password'] + X['arg_names']
X['name'] = _inject_args(X['name'], ('String', 'String'))
```

If you change this in: 

```
auth_args = [x for x in authenticated.__code__.co_varnames[:authenticated.__code__.co_argcount]]
X['arg_names'] = auth_args + X['arg_names']
X['name'] = _inject_args(X['name'], tuple(["String"]) * len(auth_args))
```

It would dynamically use the arguments that you define in the handler in ...method.(...authenticated=check_auth). The tuple(["String"]) \* len(auth_args) would however assume that the arguments used are always Strings. But i don't see why not. In that way you could use:

```
def check_auth(token):
    <do some magic token checking here for example>
```

Or any other means of authentication, instead of username and password, with any arbitrary number of arguments without having to declare them specifically in every decorator (as i saw in the Issue related to this one) , which seems a bit more DRY to me. 
## 

update: added 
    [:authenticated.**code**.co_argcount]
To only extract the agruments passed to the check_auth function, and not the internal variables

**Comment by nycholas** [comment]
duplicate #39
