### ISSUE TITLE
New major library version

### ISSUE THREAD

**Issue by alexted** [cenobites/flask-jsonrpc#473]
Hi, thank you for your work, it's a great library, we use it all the company! 
Mate, I remember you promised a new version of this library with some grandiose cardinal changes. When can we expect it?
There aren't commits for the last few months, it's a little disturbing.

**Comment by nycholas** [comment]
Hi @alexted,

Are you referring to this version? 

https://github.com/cenobites/flask-jsonrpc/releases/tag/v3.0.0

Thank you!

**Comment by nycholas** [comment]
By the way, there are issues [opened](https://github.com/cenobites/flask-jsonrpc/issues) that will enhance the documentation support using [OpenRPC Specification](https://spec.open-rpc.org/), and also the API browser, are there any issue opened that are of your interesting?

**Comment by nycholas** [comment]
Yes, the first one is that: https://github.com/cenobites/flask-jsonrpc/compare/master...fix/387-get-type-hints-by-signature

I'm a little late, but all of them are opened on the issue tab.
