### ISSUE TITLE
The CSRF token is missing when enabled CsrfProtect

### ISSUE THREAD

**Issue by wanghaiqing2015** [cenobites/flask-jsonrpc#54]
from flask_wtf import CsrfProtect
CsrfProtect(app)
 
from flask_jsonrpc import JSONRPC
jsonrpc = JSONRPC(app, '/JOB/script/call/jsonrpc2') 
@jsonrpc.method('create_script_interface')
def get( ):
    pass

the result is :

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The CSRF token is missing.</p>

**Comment by oriontvv** [comment]
This helped for me:

```
csrf_protect = CsrfProtect(app)
csrf_protect.exempt('flask_jsonrpc.wrapper')
```
