### ISSUE TITLE
warning: "Legacy editable install is deprecated."

### ISSUE THREAD

**Issue by Talkless** [cenobites/flask-jsonrpc#558]
We use local copy of `flask-jsonrcp` with applied JWT patch (https://github.com/cenobites/flask-jsonrpc/issues/370#issuecomment-2310147193).

Invoking `pip install -e /local/path` results in this deprecation warning:

`DEPRECATION: Legacy editable install of Flask-JSONRPC==3.0.1 from file:///local/path/3rdparty/flask-jsonrpc (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457`

We tried upgrading `setuptools` (74.1.2 currently) but id did not helped. 
`pip` is 24.2.
Python 3.9 (as in Debian 11).

**Comment by nycholas** [comment]
The project uses the setuptools as backend to compile Python modules to C extensions using Mypyc[1]. I will see how to migrate to Flit[2] and keep the setuptools only to compile Python modules to C extensions.

Thank you for that heads-up!

[1] - https://github.com/mypyc/mypyc
[2] - https://flit.pypa.io/en/stable/

**Comment by nycholas** [comment]
@Talkless please, check if the [fix](https://github.com/cenobites/flask-jsonrpc/pull/560) solve this warning.

**Comment by Talkless** [comment]
Deprecation warning is gone, thanks!
