### ISSUE TITLE
Mypyc version is broken

### ISSUE THREAD

**Issue by andreymal** [cenobites/flask-jsonrpc#577]
You made a big mistake uploading the precompiled 3.0.1 version to PyPI — it's installed by default, and it's broken.

With mypyc, the [flask_jsonrpc.helpers.get](https://github.com/cenobites/flask-jsonrpc/blob/v3.0.1/src/flask_jsonrpc/helpers.py#L88) function does not work as intended:

```
>>> from flask_jsonrpc.helpers import get
>>> get({"id": 1}, path="id")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/src/flask_jsonrpc/helpers.py", line 131, in get
TypeError: dict object expected; got int
```

This is probably because [obj_val](https://github.com/cenobites/flask-jsonrpc/blob/v3.0.1/src/flask_jsonrpc/helpers.py#L127) variable has the `dict` type. This works fine with regular python, but causes mypyc to disallow storing non-dict values.

There are probably many more broken things that I haven't noticed. I recommend you don't upload mypyc builds to PyPI until they are 100% tested and guaranteed to work.

**Comment by andreymal** [comment]
Yeah, at least 17 tests failed when I tried to run pytest with the mypyc build

**Comment by nycholas** [comment]
Hi @andreymal,

The Mypyc version is not uploaded to PyPI, maybe is the precompiled version generated by the [cibuildwheel](https://cibuildwheel.pypa.io/en/stable/).

See the image below:

<img width="799" alt="image" src="https://github.com/user-attachments/assets/fb503b0e-8ee5-4afd-9b54-8d379df80427">

**Comment by nycholas** [comment]
@andreymal Please, share the information about your machine, such as OS, CPU, arch, and so on.

**Comment by nycholas** [comment]
I have already deleted the precompiled versions from PyPI.

Thank you!

**Comment by andreymal** [comment]
> Please, share the information about your machine, such as OS, CPU, arch, and so on.

Arch Linux x86_64 (AMD Ryzen 5 5500), Python 3.12.6 (GCC 14.2.1)

I didn't save venv or installation logs (my mistake), but I guess `Flask_JSONRPC-3.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` was installed in my case

After deleting the precompiled versions from PyPI, it seems to work fine now 👍

>maybe is the precompiled version generated by the cibuildwheel

Since the `"%s object expected; got %U"` error is [raised by mypyc](https://github.com/python/mypy/blob/v1.11.2/mypyc/lib-rt/exc_ops.c#L190), I guess cibuildwheel was using mypyc in some way (maybe unintentionally)

**Comment by nycholas** [comment]
Thank you for that! 👍

**Comment by nycholas** [comment]
@andreymal I have already changed the pipeline to include tests before building the packages, see [here](https://github.com/cenobites/flask-jsonrpc/actions/runs/11535324500). I ask you to test the version [4.0.0a4](https://test.pypi.org/manage/project/Flask-JSONRPC/release/4.0.0a4/) and see if will fix your issue.
