### ISSUE TITLE
Does not support member functions

### ISSUE THREAD

**Issue by anthonyclark-as** [cenobites/flask-jsonrpc#60]
It would be nice to not restrict this to work on plain functions or static methods.

I think a lot of people would like to use this library like this:

```py
from flask import Flask
from flask_jsonrpc import JSONRPC

class Test:
	app = Flask(__name__)
	jsonrpc = JSONRPC(app, '/api', enable_web_browsable_api=True)

	@jsonrpc.method('App.sum(Number, Number) -> Number', validate=True)
	def sum_(self, a, b):
		return a + b

	def run(host='0.0.0.0', port=3500):
		self.app.run(host=host, port=port, debug=True)

if __name__ == '__main__':
	Test().app.run()
```

![api](https://user-images.githubusercontent.com/30667935/41548576-5b0eac46-72f1-11e8-8151-d368bb842994.png)

Running curl would require 3 arguments, but it does "work":

```sh
$ curl -v -XPOST -H "Content-type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method" : "App.sum", "params":[1,1,2]}' 'http://localhost:5000/api'
{"id":1,"jsonrpc":"2.0","result":3}
```

**Comment by anthonyclark-as** [comment]
I realized this might not be the intended use, sorry for the spam!

**Comment by sr-gi** [comment]
Sorry to revive and old issue, but I'm also interested on this.

Is there any way of adding the rules without the decorators (similar to what `add_url_rule` does in Flask)?

**Comment by nycholas** [comment]
Hi,

Great feature! We added the method `JSONRPC.register(view_func, name=None, validate=True, **options)` for this purpose.

Thank you.
