### ISSUE TITLE
Parameters not see url /api/browse in decorators

### ISSUE THREAD

**Issue by RemiZOffAlex** [cenobites/flask-jsonrpc#61]
Parameters not see in decorators between

Work in url /api/browse

```
@jsonrpc.method('tag.add')
def tag_add(name):
```

Not work in url /api/browse

```
@jsonrpc.method('tag.add')
@exampleDecorator
def tag_add(name):
```

**Comment by nycholas** [comment]
Hi,

Please look a example with decorator, https://github.com/cenobites/flask-jsonrpc/blob/master/examples/decorator/decorator.py.

Thank you.

**Comment by RemiZOffAlex** [comment]
Example code

```
#!/usr/bin/env python3

from __future__ import unicode_literals

from flask import Flask
from flask_jsonrpc import JSONRPC
from functools import wraps

app = Flask(__name__)
jsonrpc = JSONRPC(app, '/api', enable_web_browsable_api=True)

def decorator(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        return func(*args, **kwargs)
    return decorated_function

@jsonrpc.method('tag.add')
def tag_add(name):
    return "OK!"

@jsonrpc.method('tag.add_decorator')
@decorator
def tag_add_decorator(name):
    return "OK!"

app.run()
```

This browse api and show modal form for input value for method **tag.add**

![screen-1](https://user-images.githubusercontent.com/3252094/42170691-ef7fd93e-7e1f-11e8-9e35-92bbde201c3f.png)

This not showing form for method **tag.add_decorator**

![screen-2](https://user-images.githubusercontent.com/3252094/42170807-3a67ff58-7e20-11e8-8f4e-53179194670d.png)

Decorator do blocked auto definition a parameters

**Comment by RemiZOffAlex** [comment]
Is not problem! In JSON-RPC decorator write param and type param

```
@jsonrpc.method('tag.add(name=str)')

@jsonrpc.method('tag.add_decorator(name=str)')
```
