### ISSUE TITLE
Incorrect path used for browse interface

### ISSUE THREAD

**Issue by BSipos-RKF** [cenobites/flask-jsonrpc#67]
When flask_jsonrpc is used with browse enabled on a non-root script path, the browse functionality does not work. It just shows a blank page with a header bar.

This appears to be due to within the file `views/browse/__init__.py` the function `index` starts with:
`url_prefix = request.path`
but if the application is not deployed to the root URL path this is not correct and should instead be:
`url_prefix = request.script_root + request.path`
as described in https://flask.palletsprojects.com/en/1.1.x/api/#incoming-request-data

**Comment by BSipos-RKF** [comment]
FYI I tested the following patch to work:
```
--- Flask-JSONRPC-0.3.1.orig/flask_jsonrpc/views/browse/__init__.py	2020-01-09 14:57:50.596964045 -0500
+++ Flask-JSONRPC-0.3.1/flask_jsonrpc/views/browse/__init__.py	2020-01-09 14:58:43.834122731 -0500
@@ -54,7 +54,7 @@
 
 @mod.route('/')
 def index():
-    url_prefix = request.path
+    url_prefix = request.script_root + request.path
     url_prefix = url_prefix if not url_prefix.endswith('/') else url_prefix[:-1]
     service_url = url_prefix.replace('/browse', '')
     return render_template('browse/index.html', service_url=service_url, url_prefix=url_prefix)
```

**Comment by nycholas** [comment]
Hi,

Added https://flask.palletsprojects.com/en/1.1.x/api/#flask.Request.script_root.

Thank you.
