### ISSUE TITLE
Use of flask-jsonrpc with gevent

### ISSUE THREAD

**Issue by giuseppe-garzotto-treebyte** [cenobites/flask-jsonrpc#69]
Hello,

do you know any issue involving use of flask-jsonrpc with gevent ?

I've realized an API that use Blueprint, following your **modular** example.
In normal way (http) it works correctly.
Using WSGIServer (https) I've always get exception **MethodNotFoundError**.

```
app = Flask(__name__)
jsonrpc = JSONRPC(app, '/api', enable_web_browsable_api=True)
http_server = WSGIServer((Config.host, Config.port), app,
                         keyfile=Config.app_path + "\privkey.pem",
                         certfile=Config.app_path + "\cacert.pem")
```

I try to put **jsonrpc** instead of **app** in the call of WSGIServer, but it doesn't work, I get back _TypeError: 'JSONRPC' object is not callable_.

Can you help me ?

Thanks in advice, best regards

Giuseppe Garzotto

**Comment by nycholas** [comment]
Hi,

I will try make a example for you, but probably doesn't works.

Thank you.

**Comment by nycholas** [comment]
Hi,

This example of use Flask-JSONRPC with gevent: https://github.com/cenobites/flask-jsonrpc/tree/release/v1.0.0/examples/gevent

Thank you.
