### ISSUE TITLE
How can I add cache control in response?

### ISSUE THREAD

**Issue by jumae** [cenobites/flask-jsonrpc#71]
Hello, make_response return error, becose my result is list.
(Error:The view function did not return a valid response.)

**Comment by nycholas** [comment]
Hi,

Can you send a example?

Thank you.

**Comment by nycholas** [comment]
Hi,

On new release (1.0.0), you will be able to use Puggable Views from Flask, like this https://github.com/cenobites/flask-jsonrpc/blob/release/v1.0.0/examples/auth/auth.py#L48.

https://flask.palletsprojects.com/en/1.1.x/views/

Thank you.
