### ISSUE TITLE
Minimum Python Client Example

### ISSUE THREAD

**Issue by sistemicorp** [cenobites/flask-jsonrpc#75]
Prior to version 1.0, for a python flask client, I was using,

    from flask_jsonrpc.proxy import ServiceProxy

based on the example [here](https://stackoverflow.com/questions/58212444/flask-with-jsonrpc-with-https-server-with-non-verifiable-cert) and [here](https://pythonhosted.org/Flask-JSONRPC/)

but `ServiceProxy` no longer imports, and I can't find any documentation on how to jsonrpc from python.

**Comment by nycholas** [comment]
Hi,

The `ServiceProxy` was removed from the code base, you can copy from [here](https://github.com/cenobites/flask-jsonrpc/blob/v0.4.0/flask_jsonrpc/proxy.py#L38) and use it.

Or, you can use the [requests](https://requests.readthedocs.io/en/master/) for this. Follow the example with consume the method `App.index` from [this](https://github.com/cenobites/flask-jsonrpc/blob/v1.0.0/run.py):

```
$ python
>>> import requests 
>>> r = requests.post('http://localhost:5000/api', json={'id': '1', 'jsonrpc': '2.0', 'method': 'App.index'})
>>> r.json()
{'id': '1', 'jsonrpc': '2.0', 'result': 'Welcome to Flask JSON-RPC'}
```

Thank you.
