### ISSUE TITLE
The "Web browsable API" page displays  incorrect request id 

### ISSUE THREAD

**Issue by manortec** [cenobites/flask-jsonrpc#84]
The request id should be the same as the response id. But， the "Web browsable API" page displays  an incorrect request id which is not  Inconsistent with the response id 。
<img width="1568" alt="web-browsable-api" src="https://user-images.githubusercontent.com/7885543/95540613-cc245b80-0a23-11eb-873d-537a9952421e.png">

**Comment by nycholas** [comment]
Hi,

This bug just affect a display page, on request and response from API it's OK.

Thank you.
