### ISSUE TITLE
Not compatible with Flask 2.0.1

### ISSUE THREAD

**Issue by codeskyblue** [cenobites/flask-jsonrpc#88]
Code

```python
#!/usr/bin/env python3
# coding: utf-8

from flask import Flask

from flask_jsonrpc import JSONRPC

# Flask application
app = Flask(__name__)

# Flask-JSONRPC
jsonrpc = JSONRPC(app, '/api', enable_web_browsable_api=True)


@jsonrpc.method('App.index')
def index() -> str:
    return 'Welcome to Flask JSON-RPC'


if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)
```

Error output

```
Traceback (most recent call last):
  File "/Users/codeskyblue/Workspace/DemoProjects/jsonrpc-demo/python-agent/run.py", line 12, in <module>
    jsonrpc = JSONRPC(app, '/api', enable_web_browsable_api=True)
  File "/opt/homebrew/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 59, in __init__
    self.init_app(app)
  File "/opt/homebrew/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 77, in init_app
    self.register_browse(app, self)
  File "/opt/homebrew/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 104, in register_browse
    create_browse(urn('browse', app.name, browse_url), jsonrpc_app.get_jsonrpc_site()),
  File "/opt/homebrew/lib/python3.9/site-packages/flask_jsonrpc/contrib/browse/__init__.py", line 38, in create_browse
    browse = Blueprint(name, __name__, template_folder='templates', static_folder='static')
  File "/opt/homebrew/lib/python3.9/site-packages/flask/blueprints.py", line 195, in __init__
    raise ValueError("'name' may not contain a dot '.' character.")
ValueError: 'name' may not contain a dot '.' character.
```

**Comment by nycholas** [comment]
Hi,

Thank you for your reporting, we will testing the project in Flask 2.0.x and add compatibility as soon as possible.

Thank you.

**Comment by codeskyblue** [comment]
Thanks for quick response. I make a little hotfix in the code and it can works for me temporary.

Change code `/opt/homebrew/lib/python3.9/site-packages/flask_jsonrpc/contrib/browse/__init__.py` 38L
```
36 def create_browse(name: str, jsonrpc_site: 'JSONRPCSite') -> Blueprint:
 37     name = name.replace(".", "_")   # hotfix here
 38     browse = Blueprint(name, __name__, template_folder='templates', static_fold    er='static')
```

**Comment by nycholas** [comment]
@codeskyblue to following Flask versions, we created two releases:

* 1.1.1 -> Release that limit to Flask>=1.0;<2.0
* 2.0.0 -> Release that support Flask>=1;<3.0 (Support Flask 2.0.x)

By registering blueprint[1] changed and new features were added like:

`Changed in version 2.0.1:` The name option can be used to change the (pre-dotted) name the
blueprint is registered with. This allows the same blueprint to be registered multiple times with
unique names for url_for.

Cannot be possible to register a blueprint name with a dot, so we need to fix this one in the old version and create a 
new version.

Thank you.


[1] - https://flask.palletsprojects.com/en/2.0.x/blueprints/#registering-blueprints

**Comment by codeskyblue** [comment]
has you release 2.0.1 version in pypi? I did't found that version.

**Comment by codeskyblue** [comment]
The error still exists when used flask-jsonrpc 2.0.0

```
Traceback (most recent call last):
  File /run.py", line 7, in <module>
    from foo import _main
  File "/foo/_main.py", line 22, in <module>
    from ._server import app
  File "/foo/_server.py", line 16, in <module>
    jsonrpc = JSONRPC(app, '/jsonrpc', enable_web_browsable_api=True)
  File "/venv/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 59, in __init__
    self.init_app(app)
  File "/venv/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 77, in init_app
    self.register_browse(app, self)
  File "/venv/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 104, in register_browse
    create_browse(urn('browse', app.name, browse_url), jsonrpc_app.get_jsonrpc_site()),
  File "/venv/lib/python3.9/site-packages/flask_jsonrpc/contrib/browse/__init__.py", line 37, in create_browse
    browse = Blueprint(name, __name__, template_folder='templates', static_folder='static')
  File "/venv/lib/python3.9/site-packages/flask/blueprints.py", line 195, in __init__
    raise ValueError("'name' may not contain a dot '.' character.")
ValueError: 'name' may not contain a dot '.' character.
```

tested with Flask 2.0.1

**Comment by nycholas** [comment]
Hi @codeskyblue,

No, just a version Flask-JSONRPC-2.0.0[1][2] with support Flas-2.0.1.


Thank you.

[1] - https://github.com/cenobites/flask-jsonrpc/releases/tag/v2.0.0
[2] - https://pypi.org/project/Flask-JSONRPC/2.0.0/

**Comment by nycholas** [comment]
> The error still exists when used flask-jsonrpc 2.0.0
> 
> ```
> Traceback (most recent call last):
>   File /run.py", line 7, in <module>
>     from foo import _main
>   File "/foo/_main.py", line 22, in <module>
>     from ._server import app
>   File "/foo/_server.py", line 16, in <module>
>     jsonrpc = JSONRPC(app, '/jsonrpc', enable_web_browsable_api=True)
>   File "/venv/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 59, in __init__
>     self.init_app(app)
>   File "/venv/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 77, in init_app
>     self.register_browse(app, self)
>   File "/venv/lib/python3.9/site-packages/flask_jsonrpc/app.py", line 104, in register_browse
>     create_browse(urn('browse', app.name, browse_url), jsonrpc_app.get_jsonrpc_site()),
>   File "/venv/lib/python3.9/site-packages/flask_jsonrpc/contrib/browse/__init__.py", line 37, in create_browse
>     browse = Blueprint(name, __name__, template_folder='templates', static_folder='static')
>   File "/venv/lib/python3.9/site-packages/flask/blueprints.py", line 195, in __init__
>     raise ValueError("'name' may not contain a dot '.' character.")
> ValueError: 'name' may not contain a dot '.' character.
> ```
> 
> tested with Flask 2.0.1

Hi @codeskyblue,

Yes, the patch is not to allow register blueprint name with a dot, and yes, to support Flask 2.0.1 and its new features[1].

```
Flask Changed in version 2.0.1: The name option can be used to change the (pre-dotted) name the
blueprint is registered with. This allows the same blueprint to be registered multiple times with
unique names for url_for.
```

Thank you.

[1] - https://flask.palletsprojects.com/en/2.0.x/blueprints/#registering-blueprints
